client_0:
  cpu: Ryzen AI 7 350
  gpu: GeForce GTX 1050 Ti
  ram_gb: 16
client_1:
  cpu: Ryzen AI 7 350
  gpu: GeForce GTX 1050 Ti
  ram_gb: 12
client_2:
  cpu: Ryzen AI 7 350
  gpu: GeForce RTX 5060 Ti
  ram_gb: 16
client_3:
  cpu: Ryzen 5 PRO 4650U
  gpu: GeForce RTX 2060 SUPER
  ram_gb: 4
client_4:
  cpu: Ryzen 7 5825U
  gpu: GeForce RTX 3060
  ram_gb: 16
