# Hardware simulation options
cpu_cores_per_client: 2
cpu_max_freq_mhz: 2400
ram_limit_gb: 4
gpu_memory_fraction: 0.5
cuda_mps_thread_percentage: 50
gpu_graphics_clock_mhz: 1500
gpu_memory_clock_mhz: 5000

# Optional paths
dataset_path: "./data"
save_model_path: "./models"
log_path: "./logs"
